package dynamicprogramming;

/**
 * TODO: Insert description here. (generated by srallabandi)
 */
public class StringInterleaving {

  public void find(String a, String b, String c) {
    if (a.length() + b.length() != c.length()) {
      System.out.println("NO");
    }
    System.out.println(find2(0, a, 0, b, 0, c));
  }

  private boolean find2(int indexA, String a, int indexB, String b, int indexC, String c) {
    if (indexC >= c.length()) {
      // what to do
      return true;
    }
    boolean isADone = indexA >= a.length() ? true : false;
    boolean isBDone = indexB >= b.length() ? true : false;
    
    //if (isDone && )
    
    if (a.charAt(indexA) != c.charAt(indexC) && b.charAt(indexA) != c.charAt(indexC)) {
      return false;
    }
    if (a.charAt(indexA) == c.charAt(indexC) && b.charAt(indexA) == c.charAt(indexC)) {
      return find2(indexA + 1, a, indexB, b, indexC + 1, c) || find2(indexA, a, indexB + 1, b, indexC + 1, c);
    }
    
    if (a.charAt(indexA) == c.charAt(indexC)) {
      return find2(indexA + 1, a, indexB, b, indexC + 1, c);
    } 
    
    return find2(indexA, a, indexB + 1, b, indexC + 1, c);
  }

}
